MvC/Controllers/AboutController.cs
using MvC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace MvC.Controllers
{
    public class AboutController : Controller
    {
        // GET: About
        public ActionResult Index()
        {
            IEnumerable<mvcAboutModel> aboutList;
            HttpResponseMessage response = GlobalVariables.WepApiClient.GetAsync("About_Malaria").Result;
            aboutList = response.Content.ReadAsAsync<IEnumerable<mvcAboutModel>>().Result;
            return View(aboutList);
        }

        public ActionResult AddOrEdit(int id = 0)
        { 
            if (id==0)
                return View(new mvcAboutModel()) ; 
            else
            {
                HttpResponseMessage response = GlobalVariables.WepApiClient.GetAsync("About_Malaria/"+id.ToString()).Result;
                return View(response.Content.ReadAsAsync<mvcAboutModel>().Result); 
            }
        }
        [HttpPost ]
        public ActionResult AddOrEdit(mvcAboutModel abt) //pssing an object of type mvcaboutmodel
        {
            if (abt.About_Malaria_ID == 0)
            {
                HttpResponseMessage response = GlobalVariables.WepApiClient.PostAsJsonAsync("About_Malaria", abt).Result;
                TempData["SuccessMessage"] = "Saved Successfully";
            } 
            else
            {
                HttpResponseMessage response = GlobalVariables.WepApiClient.PutAsJsonAsync("About_Malaria/"+abt.About_Malaria_ID, abt).Result;
                TempData["SuccessMessage"] = "Updated Successfully";
            }
            return RedirectToAction("Index");
        } 

        public ActionResult Delete(int id)
        {
            HttpResponseMessage response = GlobalVariables.WepApiClient.DeleteAsync("About_Malaria/"+id.ToString()).Result;
            TempData["SuccessMessage"] = "Deleted Successfully";
            return RedirectToAction("Index");
        }


    } 

}

MvC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MvC/Controllers/PostUpdateController.cs
using MvC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace MvC.Controllers
{
    public class PostUpdateController : Controller
    {
        // GET: PostUpdate
        public ActionResult Index()
        {
            IEnumerable<mvcPostUpdateModel> postList; 
            HttpResponseMessage response = GlobalVariables.WepApiClient.GetAsync("Post_Update").Result;  
            postList = response.Content.ReadAsAsync<IEnumerable<mvcPostUpdateModel>>().Result;
            return View(postList);
        } 


    }
}

MvC/Views/About/AddOrEdit.cshtml
@model MvC.Models.mvcAboutModel
@{
    ViewBag.Title = "AddOrEdit";
}
<br /><br />
<div class="form-body">
    @using(Html.BeginForm())
    {
        @Html.HiddenFor(model => model.About_Malaria_ID) 

        <div class="form-group">
            @Html.LabelFor(model => model.Malaria_Description, "Malaria Description") 
            @Html.EditorFor(model => model.Malaria_Description) 
            @Html.ValidationMessageFor(model => model.Malaria_Description)
        </div> 

        <div class="form-group">
            @*<input type="submit" value="Submit" class="btn-button" />*@
            <button type="submit" value=""><i class="fas fa-save" style="font-size:20px;color:darkblue"></i></button>
            <button type="reset" value="Clear"><i class="fas fa-broom" style="font-size:20px;color:darkblue"></i>Clear</button>
        </div>
    }
</div>

MvC/Views/About/Index.cshtml
@model IEnumerable<MvC.Models.mvcAboutModel> 

@{
    ViewBag.Title = "Index";
}

<br />

<p> 
    <a href="@Url.Action("AddOrEdit" , "About")" class="btn-btn-default"><i class="fas fa-plus" style="font-size:48px"></i></a>
</p>
<table  class="table table-striped">
    <thead class="table-heading" style="color:white;font-size:15px" >
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Malaria_Description)
            </th>
            <th>Actions</th>
        </tr>
    </thead>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Malaria_Description,"Malaria Description")
        </td>
        <td>
            <a href="@Url.Action("AddOrEdit" , "About" , new { id = item.About_Malaria_ID})" class="btn btn-default"><i class="fas fa-edit"></i>Edit</a>
            <a onclick="Delete(@item.About_Malaria_ID)" class="btn btn-default">Remove</a>
        </td>
    </tr>
}

</table> 

@section scripts{
    <script>
        $(function () {
            var successMessage = '@TempData["SuccessMessage"]' //passing tempdata KEy
            if (successMessage != '') //if succMsg not empty show alert
                alertify.success(successMessage); 
        });
            function Delete(id){ 
                alertify.confirm('There isnt a recycle bin', 'You sure about that?', function () {
                    window.location.href = '@Url.Action("Delete" , "About")/' + id;
                }, null);
            }
        
    </script>
    }

MvC/Views/PostUpdate/Index.cshtml
@model IEnumerable<MvC.Models.mvcPostUpdateModel>

@{
    ViewBag.Title = "Index";
}



<p>
    <a href="@Url.Action("AddOrEdit" , "PostUpdate")" class="btn-btn-default"><i class="fas fa-plus" style="font-size:48px"></i>Post new Update</a>
</p>
<table class="table table-striped">
    <thead class="table-heading" style="color:white;font-size:15px">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Post_Description)
            <th>Actions</th>
        </tr>
    </thead>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Post_Description, "Post")
            </td>
            <td>
               <a onclick="Delete(@item.Post_Update_ID)" class="btn btn-default">Remove</a>
            </td>
        </tr>
    }

</table>

@section scripts{
    <script>
        $(function () {
            var successMessage = '@TempData["SuccessMessage"]' //passing tempdata KEy
            if (successMessage != '') //if succMsg not empty show alert
                alertify.success(successMessage);
        });
            function Delete(id){
                alertify.confirm('There isnt a recycle bin', 'You sure about that?', function () {
                    window.location.href = '@Url.Action("Delete" , "About")/' + id;
                }, null);
            }

    </script>
}

MvC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous"> 
    <link href="~/Content/alertifyjs/alertify.min.css" rel="stylesheet" />
    <link href="~/Content/alertifyjs/themes/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Malaria Harrier", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                  >
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - M-Know App</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/alertify.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>