Controllers/mvcCauseController.cs
using MvC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace MvC.Controllers
{
    [Authorize]
    public class mvcCauseController : Controller
    {
        // GET: mvcCause
        public ActionResult Index()
        {
            IEnumerable<mvcCauseModel> causeList;
            HttpResponseMessage response = GlobalVariables.WepApiClient.GetAsync("Cause").Result;
            causeList = response.Content.ReadAsAsync<IEnumerable<mvcCauseModel>>().Result;
            return View(causeList);
            
        }

        public ActionResult AddOrEdit(int id = 0)
        {
            if (id == 0)
                return View(new mvcCauseModel());
            else
            {
                HttpResponseMessage response = GlobalVariables.WepApiClient.GetAsync("Cause/" + id.ToString()).Result;
                return View(response.Content.ReadAsAsync<mvcCauseModel>().Result);
            }
        }

        [HttpPost]
        public ActionResult AddOrEdit(mvcCauseModel pst) //passing an object of type mvcModel
        {
            if (pst.Cause_ID == 0)
            {
                HttpResponseMessage response = GlobalVariables.WepApiClient.PostAsJsonAsync("Cause", pst).Result;
                TempData["SuccessMessage"] = "Saved Successfully";
            }
            else
            {
                HttpResponseMessage response = GlobalVariables.WepApiClient.PutAsJsonAsync("Cause/" + pst.Cause_ID, pst).Result;
                TempData["SuccessMessage"] = "Updated Successfully";
            }
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            HttpResponseMessage response = GlobalVariables.WepApiClient.DeleteAsync("Cause/" + id.ToString()).Result;
            TempData["SuccessMessage"] = "Deleted Successfully";
            return RedirectToAction("Index");
        }
    }
}

Views/mvcCause/AddOrEdit.cshtml
@model MvC.Models.mvcCauseModel
@{
    ViewBag.Title = "AddOrEdit";
}
<head>
    <link href="~/PortView/css/style.css" rel='stylesheet' type='text/css' />

    <link href="//fonts.googleapis.com/css?family=PT+Sans+Narrow:400,700" rel="stylesheet">
</head>
<br /><br />

<div class="form-body">
    @using (Html.BeginForm())
    {
        @Html.HiddenFor(model => model.Cause_ID)

    <div class="form-group">
        @Html.LabelFor(model => model.Cause_Name, "Cause Name")
        @Html.EditorFor(model => model.Cause_Name)
        @Html.ValidationMessageFor(model => model.Cause_Name)

        @Html.LabelFor(model => model.Cause_Description, "Cause Description")
        @Html.EditorFor(model => model.Cause_Description)
        @Html.ValidationMessageFor(model => model.Cause_Description)

       
    </div>

        <div class="form-group">
            @*<input type="submit" value="Submit" class="btn-button" />*@
            <button type="submit" value=""><i class="fas fa-save" style="font-size:20px;color:darkblue"></i></button>
            <button type="reset" value="Clear"><i class="fas fa-broom" style="font-size:20px;color:darkblue"></i>Clear</button>
        </div>
    }
</div>

@section scripts{
    @Scripts.Render("~/bundles/jqueryval");
}

Views/mvcCause/Index.cshtml
@model IEnumerable<MvC.Models.mvcCauseModel>

@{
    ViewBag.Title = "Index";
}

<h2>Malaria Cause </h2>
<br /><br />
      <head>
          <link href="~/PortView/css/style.css" rel='stylesheet' type='text/css' />

          <link href="//fonts.googleapis.com/css?family=PT+Sans+Narrow:400,700" rel="stylesheet">
      </head>
<p>
    <a href="@Url.Action("AddOrEdit" , "mvcCause")" class="btn-btn-default"><i class="fas fa-plus" style="font-size:48px"></i></a>
</p>
<table class="table table-hover table-dark">
    <thead class="table-heading" style="color:white;font-size:15px">
        <tr>

            <th>
               Cause Name
            </th>
            <th>
               Cause Description
            </th>
            <th>Actions</th>
        </tr>
        </thead>

        @foreach (var item in Model)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.Cause_Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cause_Description)
                </td>
                <td>
                    <a href="@Url.Action("AddOrEdit" , "mvcCause" , new { id = item.Cause_ID})" class="btn btn-default"><i class="fas fa-edit"></i>Edit</a>
                    <a onclick="Delete(@item.Cause_ID)" class="btn btn-default">Remove</a>
                </td>
            </tr>
        }

</table>
@section scripts{
    <script>
        $(function () {
            var successMessage = '@TempData["SuccessMessage"]' //passing tempdata KEy
            if (successMessage != '') //if succMsg not empty show alert
                alertify.success(successMessage);
        });
            function Delete(id){
                alertify.confirm('There isnt a recycle bin', 'You sure about that?', function () {
                    window.location.href = '@Url.Action("Delete" , "mvcCause")/' + id;
                }, null);
            }

    </script>
}