Controllers/mvcFAQController.cs
using MvC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace MvC.Controllers
{
    [Authorize]
    public class mvcFAQController : Controller
    {
        // GET: mvcFAQ
        public ActionResult Index()
        {
            IEnumerable<mvcFAQModel> faqList;
            HttpResponseMessage response = GlobalVariables.WepApiClient.GetAsync("FAQ").Result;
            faqList = response.Content.ReadAsAsync<IEnumerable<mvcFAQModel>>().Result;
            return View(faqList);
        }

        public ActionResult AddOrEdit(int id = 0)
        {
            if (id == 0)
                return View(new mvcFAQModel());
            else
            {
                HttpResponseMessage response = GlobalVariables.WepApiClient.GetAsync("FAQ/" + id.ToString()).Result;
                return View(response.Content.ReadAsAsync<mvcFAQModel>().Result);
            }
        }

        [HttpPost]
        public ActionResult AddOrEdit(mvcFAQModel pst) //passing an object of type mvcModel
        {
            if (pst.FAQ_ID == 0)
            {
                HttpResponseMessage response = GlobalVariables.WepApiClient.PostAsJsonAsync("FAQ", pst).Result;
                TempData["SuccessMessage"] = "Saved Successfully";
            }
            else
            {
                HttpResponseMessage response = GlobalVariables.WepApiClient.PutAsJsonAsync("FAQ/" + pst.FAQ_ID, pst).Result;
                TempData["SuccessMessage"] = "Updated Successfully";
            }
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            HttpResponseMessage response = GlobalVariables.WepApiClient.DeleteAsync("FAQ/" + id.ToString()).Result;
            TempData["SuccessMessage"] = "Deleted Successfully";
            return RedirectToAction("Index");
        }
    }
}

Views/mvcFAQ/AddOrEdit.cshtml
@model MvC.Models.mvcFAQModel
@{
    ViewBag.Title = "AddOrEdit";
}
<head>
    <link href="~/PortView/css/style.css" rel='stylesheet' type='text/css' />

    <link href="//fonts.googleapis.com/css?family=PT+Sans+Narrow:400,700" rel="stylesheet">
</head>
<<br /><br />

<div class="form-body">
    @using (Html.BeginForm())
    {
        @Html.HiddenFor(model => model.FAQ_ID)

    <div class="form-group">
        @Html.LabelFor(model => model.FAQ_Question, "Question")
        @Html.EditorFor(model => model.FAQ_Question)
        @Html.ValidationMessageFor(model => model.FAQ_Question)

        @Html.LabelFor(model => model.FAQ_Answer, "Answer")
        @Html.EditorFor(model => model.FAQ_Answer)
        @Html.ValidationMessageFor(model => model.FAQ_Answer)


    </div>

        <div class="form-group">
            @*<input type="submit" value="Submit" class="btn-button" />*@
            <button type="submit" value=""><i class="fas fa-save" style="font-size:20px;color:darkblue"></i></button>
            <button type="reset" value="Clear"><i class="fas fa-broom" style="font-size:20px;color:darkblue"></i>Clear</button>
        </div>
    }
</div>

@section scripts{
    @Scripts.Render("~/bundles/jqueryval");
}
h2>

Views/mvcFAQ/Index.cshtml
@model IEnumerable<MvC.Models.mvcFAQModel>

@{
    ViewBag.Title = "Index";
}
<head>
    <link href="~/PortView/css/style.css" rel='stylesheet' type='text/css' />

    <link href="//fonts.googleapis.com/css?family=PT+Sans+Narrow:400,700" rel="stylesheet">
</head>
<h2>Frequently asked questions</h2>

<br /><br />

<p>
    <a href="@Url.Action("AddOrEdit" , "mvcFAQ")" class="btn-btn-default"><i class="fas fa-plus" style="font-size:48px"></i></a>
</p>
<table class="table table-hover table-dark">
    <thead class="table-heading" style="color:white;font-size:15px">
        <tr>

            <th>
                Question
            </th>
            <th>
                Answer
            </th>
            <th>Actions</th>
        </tr>
    </thead>

    @foreach (var item in Model)
    {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.FAQ_Question)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FAQ_Answer)
            </td>
            <td>
                <a href="@Url.Action("AddOrEdit" , "mvcFAQ" , new { id = item.FAQ_ID})" class="btn btn-default"><i class="fas fa-edit"></i>Edit</a>
                <a onclick="Delete(@item.FAQ_ID)" class="btn btn-default">Remove</a>
            </td>
        </tr>
    }

</table>

@section scripts{
    <script>
        $(function () {
            var successMessage = '@TempData["SuccessMessage"]' //passing tempdata KEy
            if (successMessage != '') //if succMsg not empty show alert
                alertify.success(successMessage);
        });
            function Delete(id){
                alertify.confirm('There isnt a recycle bin', 'You sure about that?', function () {
                    window.location.href = '@Url.Action("Delete" , "mvcFAQ")/' + id;
                }, null);
            }

    </script>
}