Controllers/mvcHelpController.cs
using MvC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace MvC.Controllers
{
    [Authorize]
    public class mvcHelpController : Controller
    {
        // GET: mvcHelp
            public ActionResult Index()
            {
                IEnumerable<mvcHelpModel> helpList;
                HttpResponseMessage response = GlobalVariables.WepApiClient.GetAsync("Help_Line").Result;
                helpList = response.Content.ReadAsAsync<IEnumerable<mvcHelpModel>>().Result;
                return View(helpList);
            }

        public ActionResult AddOrEdit(int id = 0)
        {
            if (id == 0)
                return View(new mvcHelpModel());
            else
            {
                HttpResponseMessage response = GlobalVariables.WepApiClient.GetAsync("Help_Line/" + id.ToString()).Result;
                return View(response.Content.ReadAsAsync<mvcHelpModel>().Result);
            }
        }

        [HttpPost]
        public ActionResult AddOrEdit(mvcHelpModel pst) //passing an object of type mvcModel
        {
            if (pst.Help_Line_ID == 0)
            {
                HttpResponseMessage response = GlobalVariables.WepApiClient.PostAsJsonAsync("Help_Line", pst).Result;
                TempData["SuccessMessage"] = "Saved Successfully";
            }
            else
            {
                HttpResponseMessage response = GlobalVariables.WepApiClient.PutAsJsonAsync("Help_Line/" + pst.Help_Line_ID, pst).Result;
                TempData["SuccessMessage"] = "Updated Successfully";
            }
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            HttpResponseMessage response = GlobalVariables.WepApiClient.DeleteAsync("Help_Line/" + id.ToString()).Result;
            TempData["SuccessMessage"] = "Deleted Successfully";
            return RedirectToAction("Index");
        }



    }
}

Views/mvcHelp/AddOrEdit.cshtml
@model MvC.Models.mvcHelpModel
@{
    ViewBag.Title = "AddOrEdit";
}
<head>
    <link href="~/PortView/css/style.css" rel='stylesheet' type='text/css' />

    <link href="//fonts.googleapis.com/css?family=PT+Sans+Narrow:400,700" rel="stylesheet">
</head>
<<br /><br />

<div class="form-body">
    @using (Html.BeginForm())
    {
        @Html.HiddenFor(model => model.Help_Line_ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Help_Line_Practioner, "Practioner Details")
            @Html.EditorFor(model => model.Help_Line_Practioner)
            @Html.ValidationMessageFor(model => model.Help_Line_Practioner)

            @Html.LabelFor(model => model.Help_Line_Contact, "Contacts")
            @Html.EditorFor(model => model.Help_Line_Contact)
            @Html.ValidationMessageFor(model => model.Help_Line_Contact)


        </div>

        <div class="form-group">
            @*<input type="submit" value="Submit" class="btn-button" />*@
            <button type="submit" value=""><i class="fas fa-save" style="font-size:20px;color:darkblue"></i></button>
            <button type="reset" value="Clear"><i class="fas fa-broom" style="font-size:20px;color:darkblue"></i>Clear</button>
        </div>
    }
</div>

@section scripts{
    @Scripts.Render("~/bundles/jqueryval");
}
h2>

Views/mvcHelp/Index.cshtml
@model IEnumerable<MvC.Models.mvcHelpModel>

@{
    ViewBag.Title = "Index";
}
<head>
    <link href="~/PortView/css/style.css" rel='stylesheet' type='text/css' />

    <link href="//fonts.googleapis.com/css?family=PT+Sans+Narrow:400,700" rel="stylesheet">
</head>
<h2>Help offered by medical practioners</h2>

<br /><br />

<p>
    <a href="@Url.Action("AddOrEdit" , "mvcHelp")" class="btn-btn-default"><i class="fas fa-plus" style="font-size:48px"></i></a>
</p>
<table class="table table-hover table-dark">
    <thead class="table-heading" style="color:white;font-size:15px">
        <tr>

            <th>
                Help Line Contact
            </th>
            <th>
                Help Line Practioner
            </th>
            <th>Actions</th>
        </tr>
    </thead>


    @foreach (var item in Model)
    {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.Help_Line_Contact)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Help_Line_Practioner)
            </td>
            <td>
                <a href="@Url.Action("AddOrEdit" , "mvcHelp" , new { id = item.Help_Line_ID})" class="btn btn-default"><i class="fas fa-edit"></i>Edit</a>
                <a onclick="Delete(@item.Help_Line_ID)" class="btn btn-default">Remove</a>
            </td>
        </tr>
    }

</table>

@section scripts{
    <script>
        $(function () {
            var successMessage = '@TempData["SuccessMessage"]' //passing tempdata KEy
            if (successMessage != '') //if succMsg not empty show alert
                alertify.success(successMessage);
        });
            function Delete(id){
                alertify.confirm('There isnt a recycle bin', 'You sure about that?', function () {
                    window.location.href = '@Url.Action("Delete" , "mvcHelp")/' + id;
                }, null);
            }

    </script>
}